setup: |
  echo "🐊 Attempt to install ruff"
  echo "🐊 Will not re-install if already installed"
  pipx install ruff
targets:
  PLO1:
    - R: 80          # Expressed as a percentage
  PLO2:
    - R: 80          # Expressed as a percentage
thresholds:
  PLO1:
    - I: 2           # Expressed as a raw number of checks
    - D: 3           # Expressed as a raw number of checks 
    - R: 4           # Expressed as a raw number of checks
    - P: 6           # Expressed as a raw number of checks
  PLO2:
    - I: 2           # Expressed as a raw number of checks
    - D: 3           # Expressed as a raw number of checks
    - R: 4           # Expressed as a raw number of checks
    - P: 6           # Expressed as a raw number of checks
---
- README.md:
    - description: Ensure that a README.md files exist
      check: ConfirmFileExists
    - description: No TODOs remain in the README.md files
      check: MatchFileFragment
      options:
        fragment: "TODO"
        count: 0
        exact: true
      objectives:
        CLO2:
          degree:
            - SE: "I"
              rationale: ""
        CLO3:
          degree:
            - SE: "I"
              rationale: ""
        CLO4:
          degree:
            - SE: "I"
              rationale: ""

- writing/index.html:
    - description: Ensure that a index.html files exist
      check: ConfirmFileExists
    - description: <table> remain in the README.md files
      check: MatchFileFragment
      options:
        fragment: "<table>"
        count: 1
        exact: true
      objectives:
        CLO2:
          degree:
            - SE: "I"
              rationale: ""
        CLO4:
          degree:
            - SE: "I"
              rationale: ""
    - description: <img> remain in the README.md files
      check: MatchFileFragment
      options:
        fragment: "<img>"
        count: 1
        exact: true
      objectives:
        CLO2:
          degree:
            - SE: "I"
              rationale: ""
        CLO4:
          degree:
            - SE: "I"
              rationale: ""
    - description: <ul> remain in the README.md files
      check: MatchFileFragment
      options:
        fragment: "<ul>"
        count: 1
        exact: true
      objectives:
        CLO2:
          degree:
            - SE: "I"
              rationale: ""
        CLO4:
          degree:
            - SE: "I"
              rationale: ""

- writing/final.md:
    - description: Ensure that a final.md files exist
      check: ConfirmFileExists
      objectives:
        CLO2:
          degree:
            - SE: "I"
              rationale: ""
        CLO4:
          degree:
            - SE: "I"
              rationale: ""

# count number of commits in the GitHub repository
- description: Have at least 3 of commits in repository
  check: CountCommits
  options:
    count: 3
  objectives:
  CLO2:
    degree:
      - SE: "I"
        rationale: ""
  CLO3:
    degree:
      - SE: "I"
        rationale: ""
